-- create table for staging layer
CREATE TABLE STG_CUSTOMER (
  CUSTOMER_ID NUMBER, 
	FIRST_NAME VARCHAR2(100), 
	LAST_NAME VARCHAR2(100), 
	EMAIL VARCHAR2(250), 
	GENDER VARCHAR2(10), 
	CITY VARCHAR2(50), 
	PHONE VARCHAR2(30)
);
