-- create table for staging layer
CREATE TABLE STG_CUSTOMER (
        CUSTOMER_ID NUMBER, 
	FIRST_NAME VARCHAR2(100), 
	LAST_NAME VARCHAR2(100), 
	GENDER VARCHAR2(6),
	BIRTHDAY VARCHAR2(10), 
	STREET VARCHAR2(50), 
	CITY VARCHAR2(50), 
	STATE VARCHAR2(2),
	ZIP NUMBER,
	CCNUMBER NUMBER,
	EMAIL VARCHAR2(250)
);
