-- Insert into Reference table

INSERT INTO R_CATEGORY (CATEGORY_HAL_ID, LOADDATE, RECORD_SOURCE, CATEGORY, COMPANY, COMPANY_GROUP)
SELECT DISTINCT HAL_ID
     , current_date
     , 'Flinkster'
     , f.CATEGORY
     , f.COMPANY
     , f.COMPANY_GROUP
FROM   STG_CATEGORY_CARSHARING f
WHERE  f.HAL_ID NOT in (SELECT CATEGORY_HAL_ID FROM R_CATEGORY);
