-- Insert into SAT tables
-- Limit data to Stuttgart
-- Caution: for simplicity reasons there is not history and no check for duplicates during loads
truncate table S_BOOKING_FLK;
truncate table S_CUSTOMER_CRM;
truncate table S_RENTAL_ZONE_FLK;
truncate table S_VEHICLE_FLK;

INSERT INTO S_BOOKING_FLK (H_BOOKING_KEY, LOADDATE, RECORD_SOURCE, CATEGORY_HAL_ID, DATE_BOOKING, DATE_FROM, DATE_UNTIL, COMPUTE_EXTRA_BOOKING_FEE
                          , TRAVERSE_USE, DISTANCE, START_RENTAL_ZONE, END_RENTAL_ZONE, CITY_RENTAL_ZONE, TECHNICAL_INCOME_CHANNEL)
SELECT DISTINCT standard_hash(f.BOOKING_HAL_ID, 'MD5')
     , current_date
     , 'Flinkster'
     , f.CATEGORY_HAL_ID, f.DATE_BOOKING, f.DATE_FROM, f.DATE_UNTIL, f.COMPUTE_EXTRA_BOOKING_FEE
     , f.TRAVERSE_USE, f.DISTANCE, f.START_RENTAL_ZONE, f.END_RENTAL_ZONE, f.CITY_RENTAL_ZONE, f.TECHNICAL_INCOME_CHANNEL
FROM   STG_BOOKING_CARSHARING f
WHERE f.CATEGORY_HAL_ID in (select CATEGORY_HAL_ID from R_CATEGORY)
AND   CITY_RENTAL_ZONE in ('Stuttgart', '');

INSERT INTO S_CUSTOMER_CRM (H_CUSTOMER_KEY, LOADDATE, RECORD_SOURCE, FIRST_NAME, LAST_NAME, GENDER, BIRTHDAY, STREET, CITY, STATE, ZIP, CCNUMBER, EMAIL)
SELECT DISTINCT standard_hash(f.CUSTOMER_ID, 'MD5')
     , current_date
     , 'CRM'
     , f.FIRST_NAME, f.LAST_NAME, f.GENDER, f.BIRTHDAY, f.STREET, f.CITY, f.STATE, f.ZIP, f.CCNUMBER, f.EMAIL
FROM   STG_CUSTOMER f;

INSERT INTO S_RENTAL_ZONE_FLK (H_RENTAL_ZONE_KEY, LOADDATE, RECORD_SOURCE, NAME, CODE, TYPE, CITY, COUNTRY, LATITUDE, LONGITUDE, POI_AIRPORT_X, POI_LONG_DISTANCE_TRAINS_X
                              , POI_SUBURBAN_TRAINS_X, POI_UNDERGROUND_X, ACTIVE_X, COMPANY, COMPANY_GROUP)
SELECT DISTINCT standard_hash(f.RENTAL_ZONE_HAL_ID || '#' || f.RENTAL_ZONE_HAL_SRC, 'MD5')
     , current_date
     , 'Flinkster'
     , f.NAME, f.CODE, f.TYPE, f.CITY, f.COUNTRY, f.LATITUDE, f.LONGITUDE, f.POI_AIRPORT_X, f.POI_LONG_DISTANCE_TRAINS_X
                              , f.POI_SUBURBAN_TRAINS_X, f.POI_UNDERGROUND_X, f.ACTIVE_X, f.COMPANY, f.COMPANY_GROUP
FROM   STG_RENTAL_ZONE_CARSHARING f;

INSERT INTO S_VEHICLE_FLK (H_VEHICLE_KEY, LOADDATE, RECORD_SOURCE, VEHICLE_MODEL_TYPE, VEHICLE_MANUFACTURER_NAME, VEHICLE_MODEL_NAME, VEHICLE_TYPE_NAME, REGISTRATION_PLATE
                          , SERIAL_NUMBER, KW, FUEL_TYPE_NAME, OWNERSHIP_TYPE, CAPACITY_AMOUNT, ACCESS_CONTROL_COMPONENT_TYPE, COMPANY, COMPANY_GROUP)
SELECT DISTINCT standard_hash(f.VIN, 'MD5')
     , current_date
     , 'Flinkster'
     , f.VEHICLE_MODEL_TYPE, f.VEHICLE_MANUFACTURER_NAME, f.VEHICLE_MODEL_NAME, f.VEHICLE_TYPE_NAME, f.REGISTRATION_PLATE
                          , f.SERIAL_NUMBER, f.KW, f.FUEL_TYPE_NAME, f.OWNERSHIP_TYPE, f.CAPACITY_AMOUNT, f.ACCESS_CONTROL_COMPONENT_TYPE, f.COMPANY, f.COMPANY_GROUP
FROM   STG_VEHICLE_CARSHARING f;
