-- count number of rows in tables in staging layer
select count(*), 'STG_BOOKING_CARSHARING' from STG_BOOKING_CARSHARING
UNION ALL
select count(*), 'STG_CATEGORY_CARSHARING' from STG_CATEGORY_CARSHARING
UNION ALL
select count(*), 'STG_RENTAL_ZONE_CARSHARING' from STG_RENTAL_ZONE_CARSHARING
UNION ALL
select count(*), 'STG_VEHICLE_CARSHARING' from STG_VEHICLE_CARSHARING
UNION ALL
select count(*), 'STG_CUSTOMER' from STG_CUSTOMER;
